# Generated by Django 5.1.2 on 2024-10-29 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='uploads/')),
                ('location', models.CharField(default='No location specified', max_length=20)),
                ('tel', models.CharField(default='No tel specified', max_length=15)),
                ('description', models.CharField(default='No description specified', max_length=200)),
                ('working_hours', models.CharField(default='No working hours specified', max_length=10)),
                ('type', models.CharField(choices=[('business', 'business'), ('customer', 'customer')], default='business', max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
