# Generated by Django 5.1.2 on 2024-10-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('business', 'business'), ('customer', 'customer')], max_length=20),
        ),
    ]
