# Generated by Django 5.1.2 on 2024-10-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_alter_usertype_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
