# Generated by Django 5.1.2 on 2024-10-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0003_rename_customuser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.CharField(choices=[('business', 'business'), ('customer', 'customer')], default='', max_length=20),
        ),
    ]
