# Generated by Django 5.1.2 on 2024-10-29 23:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0004_alter_usertype_description_alter_usertype_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserType',
            new_name='CustomProfile',
        ),
    ]
