# Generated by Django 5.1.2 on 2024-10-31 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0005_rename_usertype_customprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customprofile',
            name='email',
        ),
    ]
