# Generated by Django 5.1.2 on 2024-10-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0006_remove_customprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
