# Generated by Django 5.1.2 on 2024-11-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0008_alter_customprofile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='description',
            field=models.CharField(default='Keine Beschreibung angegeben', max_length=200),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='location',
            field=models.CharField(default='Kein Standort angegeben', max_length=20),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='working_hours',
            field=models.CharField(default='Keine Verfügbarkeit angegeben', max_length=10),
        ),
    ]
