# Generated by Django 5.1.2 on 2024-12-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0010_customprofile_single_user_alter_customprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customprofile',
            name='single_user',
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
