# Generated by Django 5.1.2 on 2024-12-06 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0011_remove_customprofile_single_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='single_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
