# Generated by Django 5.1.2 on 2024-12-11 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0012_customprofile_single_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='tel',
            field=models.CharField(default='Keine tel angegeben', max_length=15, validators=[django.core.validators.RegexValidator(message="Die Telefonnummer muss mit einem '+' beginnen. Nur die Ziffern von 0-9 dürfen enthalten sein und maximal 15 Ziffern lang sein.", regex='^\\+[0-9]{1,15}$')]),
        ),
    ]
