# Generated by Django 5.1.2 on 2024-11-26 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0015_offer_user_alter_offer_user_details'),
        ('orders_app', '0005_alter_order_business_user_alter_order_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer_detail_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_app.offerdetail'),
        ),
    ]
