# Generated by Django 5.1.2 on 2024-11-27 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0006_alter_order_offer_detail_id'),
        ('registration_app', '0009_alter_customprofile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='business_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration_app.customprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_user',
            field=models.IntegerField(null=True),
        ),
    ]
