# Generated by Django 5.1.2 on 2024-11-27 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0015_offer_user_alter_offer_user_details'),
        ('orders_app', '0007_alter_order_business_user_alter_order_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='business_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_app.offer'),
        ),
    ]
