# Generated by Django 5.1.2 on 2024-11-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0008_alter_order_business_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='business_user',
            field=models.IntegerField(null=True),
        ),
    ]
