# Generated by Django 5.1.2 on 2024-11-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='url',
            field=models.URLField(),
        ),
    ]
