# Generated by Django 5.1.2 on 2024-11-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_alter_offerdetail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
