# Generated by Django 5.1.2 on 2024-11-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_alter_offer_title_alter_offerdetail_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
