# Generated by Django 5.1.2 on 2024-11-09 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_alter_offer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_app.offerdetail'),
        ),
    ]
