# Generated by Django 5.1.2 on 2024-11-09 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0008_remove_offer_details_offerdetail_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdetail',
            old_name='details',
            new_name='offer',
        ),
    ]
