# Generated by Django 5.1.2 on 2024-12-07 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0015_offer_user_alter_offer_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='url',
        ),
    ]
