# Generated by Django 5.1.2 on 2024-11-29 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers_app', '0015_offer_user_alter_offer_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('description', models.TextField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_app.offer')),
            ],
        ),
    ]
