# Generated by Django 5.1.2 on 2024-11-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0003_alter_review_business_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='business_user',
            field=models.IntegerField(null=True),
        ),
    ]
